language: cpp
cache: apt
os:
    - linux
    - osx
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - if [ "${COVERALLS}" = "true" ]; then
        sudo pip install cpp-coveralls ;
        sudo apt-get install luarocks ;
        sudo luarocks install luacov-coveralls ;
      fi
install:
    - sudo apt-get install -qq clang-3.4
    - sudo apt-get install -qq g++-4.8
    - sudo apt-get install libboost1.48-all-dev
    - $CXX_COMPILER --version
    - CXX=$CXX_COMPILER ./bootstrap/unix.sh
script:
    - cat cov-int/scm_log.txt || echo "No coverity log"
    - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
        if [ "${COVERALLS}" = "true" ]; then
            /tmp/configure build cxx=${CXX_COMPILER} coverage=true;
            make -C build;
            make -C build check;
        else
            /tmp/configure build cxx=${CXX_COMPILER};
            make -C build;
            make -C build check;
        fi
      else
        cat cov-int/scm_log.txt ;
      fi
after_success:
    - if [ "${COVERALLS}" = "true" ]; then
        ${GCOV} --version ;
        coveralls --gcov ${GCOV} --exclude lua --exclude test --gcov-options '\-lp' ;
      fi
git:
    submodules: false
env:
    matrix:
        - CXX_COMPILER=g++-4.8
        - CXX_COMPILER=clang++
        - CXX_COMPILER=g++-4.8 GCOV=gcov-4.8 COVERALLS=true
    global:
        - secure: "IrxBokk6LuQHHGb2Ykyi9AYJnoFwQ9ua4iBQe+nPvjZfKyxoVWyHVI8rn5hbV7PupM6PIMn0hmMXVHsRVH9eWfCTMXr+Qo8zO6B0DNsNRtAnig7ZS3RpO93C/N8rUjrlE3GV6ZyeXHGNj6naSIJtwH//IEMpJNTGrqt9cB9UZbw="
        - CONFIGURE_LIBRARY_DIR=${TRAVIS_BUILD_DIR}/src/lib

addons:
  coverity_scan:
    project:
      name: "hotgloupi/configure"
      description: "Configure your projects' builds"
    notification_email: raphael.londeix+github@gmail.com
    build_command_prepend: "/tmp/configure build cxx=$CXX_COMPILER"
    build_command: "make -C build"
    branch_pattern: coverity
