version: 0.0.0-{build}

#os: Visual Studio 2014 CTP4

branches:
    only:
        - master

init:
    - git config --global core.autocrlf input

platform:
    - x86

install:
    - SET PYTHON=C:/Python27
    - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
    - "%PYTHON%/python.exe C:/get-pip.py"
    - SET PIP="%PYTHON%/Scripts/pip.exe"
    - "%PIP% --version"
    - "%PIP% install behave"
    - SET BEHAVE="%PYTHON%/Scripts/behave.exe"
    - "%BEHAVE% --version"
    - CALL "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/vcvarsall.bat" x86
    - SET CONFIGURE_LIBRARY_DIR=%APPVEYOR_BUILD_FOLDER%/src/lib
    - git submodule update --init --recursive

before_build:
    - cmd: SET
    - bash bootstrap/vs.sh

build_script:
    - configure.exe build BOOST_INCLUDE_DIR="c:/Libraries/boost" BOOST_LIBRARY_DIR="c:/Libraries/boost/stage/lib" -d --build --target package --plugin package.archive package-name=configure-win32

artifacts:
    - path: build/configure-win32.zip
      name: package

test_script:
    - configure.exe build --build --target check
    - SET CONFIGURE_EXE=%APPVEYOR_BUILD_FOLDER%/build/bin/configure.exe
    - "%BEHAVE% test/features -q -m -k"

deploy:
  provider: GitHub
  auth_token:
    secure: aNNADwq2sOOL4wtFqX8qdutn+moJCs84o2LYyiQJtxvcpuD9sNMT0r3YQ/JdsQeR
  artifact: package
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
