version: 0.0.0-{build}

#os: Visual Studio 2014 CTP4

branches:
    only:
        - master

init:
    - git config --global core.autocrlf input

platform:
    - x86

install:
    - SET PYTHON=C:/Python27
    - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
    - "%PYTHON%/python.exe C:/get-pip.py"
    - SET PIP="%PYTHON%/Scripts/pip.exe"
    - "%PIP% --version"
    - "%PIP% install behave"
    - SET BEHAVE="%PYTHON%/Scripts/behave.exe"
    - "%BEHAVE% --version"
    - CALL "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/vcvarsall.bat" x86
    - SET CONFIGURE_LIBRARY_DIR=%APPVEYOR_BUILD_FOLDER%/src/lib
    - git submodule update --init --recursive
    - SET BOOST_INCLUDE_DIR=c:/Libraries/boost
    - SET BOOST_LIBRARY_DIR=c:/Libraries/boost/lib32-msvc-12.0

before_build:
    - cmd: SET
    - bash bootstrap/vs.sh

build_script:
    - configure.exe build CXX=cl.exe BOOST_INCLUDE_DIR="%BOOST_INCLUDE_DIR%" BOOST_LIBRARY_DIR="%BOOST_LIBRARY_DIR%" -d --build --target package --plugin package.archive package-name=configure-win32

artifacts:
    - path: build/configure-win32.zip
      name: package

test_script:
    - configure.exe build --build --target check
    - SET CONFIGURE_EXE=%APPVEYOR_BUILD_FOLDER%/build/bin/configure.exe
    - "%BEHAVE% test/features -q -m -k"

deploy:
  provider: GitHub
  auth_token:
    secure: 3tRrd0Tm5axIgBgv6YntPiOSYY7UJL3FgrG78KJTG6Sjp8/QkW8NxRbTKAi0+r2A
  artifact: package
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
